### PR TITLE
Changed reference frame from base to laser to account for upside down and/or back facing laserscanners

### PR DESCRIPTION
**Pull request by felix-kolbe**
Since we were having some problems with a rear facing, upside-down mounted laserscanner, we have rewritten the wrapper to use the laser-frame as base for gmapping and leave the transformation of scan-positions entirely to the wrapper class. This should make slam_gmapping much more robust to non-standard mounting positions of laserscanners.

Here is [a bag with two launch files](http://users.informatik.haw-hamburg.de/~aba879/ros/bag_scitos_2013-04-08_scan_odom_tf.tar.gz), that demonstrate the problem.
The front-scanner works fine, but the rear facing one produces a messed up map in standard gmapping.

A nice side-effect of these changes is, that gmapping can now handle panning scanners, as the base->laser transform is now dynamically included in the gmapping pose.

The .gitignore file commit slipped in but should be useful nevertheless.

A problem with non symmetrical scans (e.g. min_angle = -1, max_angle = 2) still exists and may be fixed in a future version. (This is not new, but also a problem of the current implementation.)

### CODE REVIEW

**Comment by chadrockey** [comment]
This looks like it should work, I'm not sure who the maintainer is.  I think @hershwg.

@stwirth, could you take a look at this?

**Comment by hershwg** [comment]
Sorry, I AM actually looking at this as we speak.

**Comment by hershwg** [comment]
It does indeed look promising.  I'm currently running it on some bag files which take about 30 minutes each, so please be patient. :)

**Comment by hershwg** [comment]
Thanks @felix-kolbe  and @ben-struss!

**Pull request merged**
