### PR TITLE
Fix map mutex use (gmapping issue #11)

### PR DESCRIPTION
**Pull request by skohlbr**

### CODE REVIEW

**Comment by skohlbr** [comment]
See #11. Tested with logged data as in http://wiki.ros.org/slam_gmapping/Tutorials/MappingFromLoggedData. Should I create another pull request for merging into groovy_devel?

**Comment by wjwwood** [comment]
@skohlbr Thanks I totally lost track of this, it fell through the cracks.

**Comment by wjwwood** [comment]
I'm not convinced that these are entirely necessary at all, but for now we can fix the obvious miss use and maybe look at removing them altogether at some other time.

I can back-port this to groovy.

**Comment by wjwwood** [comment]
Groovy backport: ac003dc64c3802e7f1ca5650f789aab502b35b93

**Pull request merged**
