### PR TITLE
make sure the laser sent to gmapping is always centered

### PR DESCRIPTION
**Pull request by vrabaud**

### CODE REVIEW

**Comment by 130s** [comment]
+1

I confirmed this works with turtlebot_gazebo (discussed in #34). 
Centering the angle as a solution makes more sense to me too.

**Comment by windelbouwman** [comment]
This indeed makes sense. Discarding the scan was the easy way out. Are there any unittests covering the different cases?

**Comment by vrabaud** [comment]
no unit test. Please give me a rosbag with such data (contact me on my personal email)

**Comment by windelbouwman** [comment]
Currently I have no setup to test this...

**Comment by vrabaud** [comment]
any you guys can get people from ROS to give feedback on that ? I also would like a rosbag to add as a unittest. Thx

**Comment by 130s** [comment]
@vrabaud Wasn't [this bag file](https://drive.google.com/file/d/0Bw_hbVS3wTLySDhGZ3haU2Z2WUU/view?usp=sharing) enough? It only contains `scan` (sorry I missed in [answers](http://answers.ros.org/question/210849/scan-message-must-contain-angles-from-x-to-x/?comment=213970#comment-213970) that you wanted bag to be sent via email).

**Comment by vrabaud** [comment]
I don't have time to follow ros.answers for that (there are quite a few bugs I follow ...). Thank you for making the transition with that specific question. Any positive feedback from there ?

**Comment by vrabaud** [comment]
this bag file is missing tf data to get a proper scan. I updated my merge request to be cleaner and also added a test. Please give me the full bag or try running the test with yours (only parameters should be tuned, but right now, when doing `ctest -R symm -V`, tf data cannot even be used.

**Comment by 130s** [comment]
Ok I recorded a full bag file, which is over 3GB for only 15 seconds (apparently `/camera`\* topics are large). Do you still want me to upload it to [slam_gmapping_test_data](https://github.com/ros-perception/slam_gmapping_test_data)? Or is [download.ros.org](http://wiki.ros.org/DevelopersGuide#Large_data_files.2C_Large_test_files) better?

**Comment by vrabaud** [comment]
well, we don't need the camera topics. Just strip them off and put the bag on a Google drive and share the link with me please. All that is needed I believe is the scan topic and /tf.

**Comment by vrabaud** [comment]
ok, I updated the PR but I still cannot test it: I need a bag where a robot moves.

**Comment by Tones29** [comment]
Vincent, I just posted a bag file which contains the data that you require for testing in #34. Let me know, if   you need further help.

**Comment by 130s** [comment]
FYI there's already a PR for the bag file for testing https://github.com/ros-perception/slam_gmapping_test_data/issues/1

**Comment by vrabaud** [comment]
Guys, you've been amazing at providing data. I got three sets and one of them actually helped me figure out a bug when the laser was mounted downard. here are my results:

@gbiggs
biggs

@130s 
isaac

@Tones29 
tones

Can you guys please let me know if those look about right ? if so, I'll update the test data to include some of those.

@wjwwood or @mikeferguson , any way you could review my pull request ? It is somewhat urgent as this breaks on turtlebots now.

**Comment by wjwwood** [comment]
The code is pretty tricky, but it makes sense on the face of it. The test looks ok. I'd +1 if @mikeferguson agrees.

**Comment by Tones29** [comment]
@vrabaud, the map you created looks right. Please feel free to add my dataset to the testing data, if it is helpful for you.

**Comment by gbiggs** [comment]
The map for mine is good.

**Comment by mikeferguson** [comment]
The logic seems sound -- I tried out the code before the last two commits on several old bagfiles and they worked. (you can find some ancient bagfiles for slam here: http://fergy.me/slam/)

**Pull request merged**
