### PR TITLE
Respect tf_prefix when sending maps

### PR DESCRIPTION
**Pull request by abencz**
When working with a multirobot system, setting "tf_prefix" affects the transforms published by slam_gmapping in /tf, but not the frame_id in the published maps. This patch should correct this by prepending tf_prefix to the frame id.

See also section 7.1.1 in http://www.ros.org/wiki/geometry/CoordinateFrameConventions

### CODE REVIEW

**Comment by hershwg** [comment]
I fixed this in master using resolve().  Can you please update to master and test that it does what you need?  It's hard to imagine it does not, but I'm short on time right now to run this myself with a prefix.

**Comment by abencz** [comment]
Ok, will test this. Is resolve() new in Groovy/Hydro or is it available in Fuerte as well?

**Comment by abencz** [comment]
I'm really glad resolve() is in tf as well :) I was hoping there was something like this, but couldn't find it.

**Comment by abencz** [comment]
Tested with Turtlebot & Fuerte.

**Pull request closed without merging**
