### PR TITLE
Update slam_gmapping.cpp

### PR DESCRIPTION
**Pull request by DaMalo**
Reenabled temporal update.
I can't see why it was commented out anyway. The commit where it was commented out was commit "8f48572" on Jun 27, 2013 with message "catkinize slam_gmapping". Maybe someone has more information on this matter?

### CODE REVIEW

**Comment by vrabaud** [comment]
I do not understand why I removed it in https://github.com/ros-perception/slam_gmapping/commit/8f4857243a4ab4cb82395a96d8ceae776a1984d7#diff-77a5a1f2547b3ca5f56b4725f4e77eaaR397 : all I see is that I commented out that function call while I was moving headers in an include folder to get code to compile.
This might have a lot of impact, @wjwwood  and @mikeferguson  or whoever, please provide any feedback. Thx guys.

**Comment by wjwwood** [comment]
I have no idea how this might affect the performance of gmapping. That said I can't see a reason for it being removed in the first place. Perhaps you were debugging the locking issues which came up somewhat recently and forgot to undo the comment.

**Comment by mikeferguson** [comment]
LGTM. It would appear that this comment probably caused a regression in hydro/indigo, which should be fixed. GridSlamProcessor class defaults the update period to 5.0 (seconds, I presume) (ref: https://github.com/ros-perception/openslam_gmapping/blob/89290feea99cd4204ffe30fa46835540c22b7939/gridfastslam/gridslamprocessor.cpp#L22). Whereas http://wiki.ros.org/gmapping states that temporalUpdate defaults to -1.0 (no temporal update, just update based on movement). Thus, in hydro, you update every 5 seconds (and every X meters, etc), and would thus likely increase the load while running, and also make it a lot harder to create a map if you happen to stop the robot for a while...

**Comment by vrabaud** [comment]
Thx all for your feedback. Releasing that.

**Pull request merged**
